;dfgdfgsdfgsdf
[General]
version=1.44.02
language=R2U
maintext= unreal config parser
timezone=5 ; используем GMT сдвиг
[Position]
x=150
y=200
width=800
height=550
something=
[Cat]
weight=8
color=black
[Some]
[General]
language=EN
some=223
[Apple]
pine_apple=7

